[build]
publish = "exampleSite/public"
command = "hugo -v --source=exampleSite --themesDir ../.. --gc"

[build.environment]
HUGO_VERSION = "0.89.4"
HUGO_ENV = "production"
HUGO_BASEURL = "https://what-her-name.netlify.app"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
